Selinux ignore defaults
voxpupuli/puppet-rabbitmq pull request #856
Opened 2020-08-23 18:56 UTC by tobias-urdin

It makes sure it's idempotent on RHEL based, needs an increase in systemd dependency to a minimum
versions of 2.10.0 to include the changes there.

Fixes: #836

2020-08-23 19:48 UTC, wyardley commented
@tobias-urdin can you rebase / squash, and resolve the rubocop failure?

Are there any security implications of this change?

2020-08-24 11:58 UTC, tobias-urdin commented
There is no security implications, this simply makes sure the systemd module doesn't overwrite the SELinux contexts the unit file that the installed package drops.

2020-08-24 12:09 UTC, ekohl requested changes
So I guess this is due to https://tickets.puppetlabs.com/browse/PUP-10548. It would be good to refer to that if that's the case.

2020-08-24 12:09 UTC, ekohl commented on manifests/config.pp
> +    }
It's better to use `$facts`. I think you can also simplify it further:
```suggestion
    $selinux_ignore_defaults_real = $facts['os']['family'] == 'RedHat'
```

2020-08-24 12:09 UTC, ekohl commented on spec/classes/rabbitmq_spec.rb
> +            end
This can be simplified:
```suggestion
            selinux_ignore_defaults = facts[:os]['family'] == 'RedHat'
```

2020-08-24 13:49 UTC, tobias-urdin commented
Fixed, the bug you linked is not really related. The issue occurs because the RabbitMQ packages built by the CentOS Messaging SIG drops the systemd unit file with the rabbitmq_unit_t context, the systemd modules then tries to overwrite that to systemd_unit_t.

2020-08-24 14:17 UTC, ekohl commented
So the RabbitMQ packages don't even provide the content so a restorecon would also revert it back to `systemd_unit_t`? That sounds like bad packaging. It would be good to at least mention that in the commit message, but ideally also some URL to a CentOS bug that describes it.

Other than that the PR looks good to me.

2020-08-24 14:48 UTC, tobias-urdin commented
It's not really a package bug, it's more a regression in puppet-rabbitmq that was introduced when moving to the systemd module. See the commit message on the fix back in 2015 [1].

[1] https://github.com/voxpupuli/puppet-rabbitmq/commit/0227f762070ffbbea3c28d6a60174de98fa4cc1c

2020-08-28 22:40 UTC, tobias-urdin commented
Anything missing here or are we good?

2020-08-29 15:22 UTC, igalic commented
an approving review (from somebody competent in SELinux / RHEL)

2020-08-30 14:51 UTC, ekohl approved these changes

2020-08-30 14:51 UTC, merged